backend = "etcd"
client_cakeys = "/ca/etcd/cert.pem"
client_cert = "/ca/etcd/cert.pem"
client_key = "/ca/etcd/key.pem"
confdir = "/etc/confd"
log-level = "info"
interval = 600
noop = false
scheme = "http"
watch = true
